class_name Village
extends Node3D
## A playable map: lanterns, chore stations, the bell, spawn points, named
## landmarks, and the obstacles used for collision and bot pathfinding.
##
## Map scenes are generated by tools/build_village.gd but are plain scenes:
## move markers in the editor and the game picks them up by group and name.

const CELL := 0.5
const AGENT_RADIUS := 0.4

@export var map_name := "Moonpatch Village"
@export var bounds := Rect2(-30, -30, 60, 60)

var _astar: AStarGrid2D


func _ready() -> void:
	_build_grid()


func lanterns() -> Array:
	var out := get_tree().get_nodes_in_group("lantern").filter(func(n): return is_ancestor_of(n))
	out.sort_custom(func(a, b): return a.lantern_id < b.lantern_id)
	return out


func stations() -> Dictionary:
	var out := {}
	for n in get_tree().get_nodes_in_group("station"):
		if is_ancestor_of(n):
			out[n.station_id] = n
	return out


func spawn_points() -> Array[Vector3]:
	var out: Array[Vector3] = []
	var spawns := get_node_or_null("Spawns")
	if spawns:
		for c in spawns.get_children():
			out.append((c as Node3D).global_position)
	if out.is_empty():
		out.append(Vector3.ZERO)
	return out


func bell_position() -> Vector3:
	var bell := get_node_or_null("Bell") as Node3D
	return bell.global_position if bell else Vector3.ZERO


## The nearest named place, for bot memories and meeting talk.
func landmark_name(pos: Vector3) -> String:
	var best := "the village"
	var best_d := INF
	var marks := get_node_or_null("Landmarks")
	if marks == null:
		return best
	for m in marks.get_children():
		var d := (m as Node3D).global_position.distance_squared_to(pos)
		if d < best_d:
			best_d = d
			best = String(m.name).replace("_", " ")
	return best


func landmark_positions() -> Dictionary:
	var out := {}
	var marks := get_node_or_null("Landmarks")
	if marks:
		for m in marks.get_children():
			out[String(m.name).replace("_", " ")] = (m as Node3D).global_position
	return out


func clamp_to_bounds(pos: Vector3) -> Vector3:
	return Vector3(
		clampf(pos.x, bounds.position.x + 0.5, bounds.end.x - 0.5),
		pos.y,
		clampf(pos.z, bounds.position.y + 0.5, bounds.end.y - 0.5))


func is_walkable(pos: Vector3) -> bool:
	if _astar == null:
		return true
	var c := _to_cell(pos)
	return _astar.is_in_boundsv(c) and not _astar.is_point_solid(c)


## A path of world points from `from` to `to` that avoids obstacles.
func find_path(from: Vector3, to: Vector3) -> PackedVector3Array:
	if _astar == null:
		return PackedVector3Array([to])
	var a := _nearest_open(_to_cell(from))
	var b := _nearest_open(_to_cell(to))
	var cells := _astar.get_id_path(a, b)
	var out := PackedVector3Array()
	for i in cells.size():
		# Skip every other cell; the mover smooths between points anyway.
		if i % 2 == 1 and i != cells.size() - 1:
			continue
		out.append(_to_world(cells[i]))
	if out.size() > 0 and is_walkable(to):
		out[out.size() - 1] = Vector3(to.x, 0.0, to.z)
	return out


func random_walkable_point(rng: RandomNumberGenerator) -> Vector3:
	for i in 50:
		var p := Vector3(
			rng.randf_range(bounds.position.x + 2.0, bounds.end.x - 2.0), 0.0,
			rng.randf_range(bounds.position.y + 2.0, bounds.end.y - 2.0))
		if is_walkable(p):
			return p
	return Vector3.ZERO


## Positions in a ring around the square, used when a meeting is called.
func gather_points(count: int) -> Array[Vector3]:
	var center := bell_position()
	var square := get_node_or_null("Landmarks/the_square") as Node3D
	if square:
		center = square.global_position
	var out: Array[Vector3] = []
	for i in count:
		var ang := TAU * float(i) / float(maxi(count, 1))
		out.append(center + Vector3(cos(ang), 0, sin(ang)) * 3.6)
	return out


func _build_grid() -> void:
	_astar = AStarGrid2D.new()
	_astar.region = Rect2i(0, 0, int(bounds.size.x / CELL), int(bounds.size.y / CELL))
	_astar.cell_size = Vector2.ONE
	_astar.diagonal_mode = AStarGrid2D.DIAGONAL_MODE_ONLY_IF_NO_OBSTACLES
	_astar.default_compute_heuristic = AStarGrid2D.HEURISTIC_OCTILE
	_astar.default_estimate_heuristic = AStarGrid2D.HEURISTIC_OCTILE
	_astar.update()
	for body in get_tree().get_nodes_in_group("obstacle"):
		if not is_ancestor_of(body):
			continue
		for shape_node in body.get_children():
			if shape_node is CollisionShape3D:
				_mark_shape(shape_node)


func _mark_shape(cs: CollisionShape3D) -> void:
	var xf := cs.global_transform
	var shape := cs.shape
	var half: Vector3
	var cylinder := false
	if shape is BoxShape3D:
		half = (shape as BoxShape3D).size * 0.5
	elif shape is CylinderShape3D:
		var r := (shape as CylinderShape3D).radius
		half = Vector3(r, 0, r)
		cylinder = true
	else:
		return
	var reach := maxf(half.x, half.z) * 1.5 + AGENT_RADIUS
	var c0 := _to_cell(xf.origin - Vector3(reach, 0, reach))
	var c1 := _to_cell(xf.origin + Vector3(reach, 0, reach))
	var inv := xf.affine_inverse()
	for x in range(c0.x, c1.x + 1):
		for y in range(c0.y, c1.y + 1):
			var cell := Vector2i(x, y)
			if not _astar.is_in_boundsv(cell):
				continue
			var local := inv * _to_world(cell)
			var inside := false
			if cylinder:
				inside = Vector2(local.x, local.z).length() <= half.x + AGENT_RADIUS
			else:
				inside = absf(local.x) <= half.x + AGENT_RADIUS and absf(local.z) <= half.z + AGENT_RADIUS
			if inside:
				_astar.set_point_solid(cell, true)


func _nearest_open(cell: Vector2i) -> Vector2i:
	cell = cell.clamp(_astar.region.position, _astar.region.end - Vector2i.ONE)
	if not _astar.is_point_solid(cell):
		return cell
	for r in range(1, 12):
		for dx in range(-r, r + 1):
			for dy in range(-r, r + 1):
				var c := cell + Vector2i(dx, dy)
				if _astar.is_in_boundsv(c) and not _astar.is_point_solid(c):
					return c
	return cell


func _to_cell(pos: Vector3) -> Vector2i:
	return Vector2i(
		int(floor((pos.x - bounds.position.x) / CELL)),
		int(floor((pos.z - bounds.position.y) / CELL)))


func _to_world(cell: Vector2i) -> Vector3:
	return Vector3(
		bounds.position.x + (cell.x + 0.5) * CELL, 0.0,
		bounds.position.y + (cell.y + 0.5) * CELL)
